### ISSUE TITLE
Cohort Operations highlighting missing and " auth_mcae" no longer appended to the component column

### ISSUE THREAD

**Issue by acheckley** [danmarsden/moodle-auth_mcae#12]
Hi Kamat,

Upon upgrade to Moodle 2.2 to 2.6 and in the Cohort Operations menu, it is no longer defaulting to the auth_mcae type when generating the new cohort. It's adding students in the manual form.

The newly generated cohorts run as manual cohorts but with users being automatically added in the same style as the auth_mcae cohorts. This isn't a problem for me because I like the way in which I can manually add users via the main cohort whilst having the mcae plugin adding users at the same time. It actually works better in some circumstances.

However, I remember previously that new cohorts would start out as an auth_mcae cohort which, if you wanted to stop the automated process, you could then convert to a manual cohort.

Ideally, all of these options would be good.

**Comment by danmarsden** [comment]
I can't reproduce the issues described, please make sure you are using the latest code and a supported Moodle release. If you are still having issues please let us know the exact moodle version you are using and possibly some screenshots of the issues. thanks.

**Comment by acheckley** [comment]
Hi Dan, cheers for looking at this. It is a fantastic plugin. I'll follow this up early next year and let you know.
