### ISSUE TITLE
No matching with "multiselect" profile field

### ISSUE THREAD

**Issue by federicama** [danmarsden/moodle-auth_mcae#13]
Hi, thanks for the plugin, it is really useful! 
I have a problem using it, though. I installed the plugin "Multi select menu custom profile field" (https://moodle.org/plugins/view.php?plugin=profilefield_multiselect) to allow the users to select multiple options in the registration form. 
When I try to create cohorts from that custom field I don't see the " %profile_field_raw_name" option  but only the "%profile_field_name". In this way I cannot use the %split option to create multiple cohorts from a multiple selection.
Is it a problem of the plugin or am I doing something wrong?

Thanks for the attention!

**Comment by danmarsden** [comment]
I'm not sure what you are asking for here - this plugin can only read the information that is stored in the raw field by that profile field plugin - it can't do any translation of the data using specific logic or custom fields used by the custom plugin.
