### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by twistd** [danmarsden/moodle-auth_mcae#25]
Hi all,

I have installed the plugin and setup (hopefully correctly). However when I go to /auth/mcae/convert.php or /auth/mcae/view.php I get a 500 error.

Also I haven't worked out where to put the code as our theme doesn't have default.php or general.php

Any help would be appreciated. Thanks!

**Comment by danmarsden** [comment]
not enough information here - closing for now. If you still have this issue please elevate your debugging settings and provide more information on the error message received.
