### ISSUE TITLE
offer to pick up maintenance

### ISSUE THREAD

**Issue by danmarsden** [danmarsden/moodle-auth_mcae#27]
Hi @kamat - I see you've put this plugin up for adoption in the Moodle community - if that's still the case I'd be happy to take over as we have a few improvements we'd like to add and I'd prefer not to maintain a separate version of the codebase. Of course I'll leave all existing copyright statements in place and include your details as the previous maintainer of the plugin.

If you're happy for me to take over maintenance of this plugin would you mind transferring this repository to me? - that way all existing forks will also get updated to point to my repo. To transfer ownership you hit the settings tab up the top and then down the bottom use the "transfer ownership" button. Thanks!

**Comment by kamat** [comment]
Hi @danmarsden 
Thank you for your offer. I'm happy to transfer this repo to you.

Good luck!

**Comment by kamat** [comment]
An error appears: 'danmarsden/moodle-auth_mcae already exists'
GitHub Help says: "The target account must not have a repository with the same name, or a fork in the same network."

**Comment by kamat** [comment]
I try to rename repo and receive this error "danmarsden already has a repository in the kamat/moodle-auth_mcae0 network"

**Comment by danmarsden** [comment]
whoops - sorry about that, I forgot to delete my local fork. I've just deleted it so hopefully it should work now. Thanks for your work on this plugin and for being willing to share it.

**Comment by kamat** [comment]
Repository transfer to danmarsden requested

**Comment by danmarsden** [comment]
Thanks! - transfer complete.
