### ISSUE TITLE
Cohort Operations -> Deleting Cohorts: Error

### ISSUE THREAD

**Issue by Kathrin84** [danmarsden/moodle-auth_mcae#9]
When I made cohorts with your plugin and I want to delete them (all or just a single one), I always get an error:

![screenshot 2014-12-23 08 31 51](https://cloud.githubusercontent.com/assets/4711883/5535478/9da53470-8a7f-11e4-8511-4eb34e2bce2c.png)

When continuing, a single cohort is deleted. Also if I marked all cohorts for delete, just a single one is gone.

It would be great if it would be possible to delete all marked cohorts with one step as it was intended with this option, I assume.

**Comment by acheckley** [comment]
Hi Kathrin84,

The work around is to delete using the main Site Administration --> Users --> Accounts --> Cohorts and delete. This seems to work nicely.

**Comment by acheckley** [comment]
Hi Kathrin84,

The work around is to delete using the main Site Administration --> Users --> Accounts --> Cohorts and delete. This seems to work nicely.

**Comment by danmarsden** [comment]
I can't reproduce this. the convert.php script provided by the auth mcae plugin seems to allow deleting multiple cohorts so I assume this is not an issue anymore. Please provide more information if there is still a problem and I can take another look. Thanks.

**Comment by acheckley** [comment]
Hi Dan, thank you for looking at this again. I don't know if this is still an issue either because I hard coded the work around into my Moodle. I'll test it out later again this year and let you know.
